[package]
name = "rust_api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
# sqlx with postgres and runtime-tokio features
sqlx = { version = "0.8", features = ["runtime-tokio-native-tls", "postgres", "json"] }
# redis with async tokio features
redis = { version = "0.27", features = ["tokio-comp"] }
dotenvy = "0.15" # Added for .env file handling